export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appName: "Tasbeeh", appSub: "Digital Prayer Counter", tapHint: "Tap anywhere on the circle",
    today: "Today", cycles: "Cycles", current: "Current", reset: "Reset Counter",
    completed: "Completed", nextLoading: "Next dhikr loading...",
    duaTitle: "Supplications", duaSub: "Supplications & Remembrance",
    backToAll: "Back to all du'a", listen: "Listen",
    statsTitle: "Statistics", statsSub: "Your Personal Progress",
    signInUnlock: "Sign in to unlock full stats",
    signInDesc: "Track your daily, weekly, and monthly dhikr progress across all your devices.",
    signInFree: "Sign In Free", thisMonth: "This Month", streak: "Streak",
    bestDay: "Best Day", totalAll: "Total All Time", days: "days", keepGoing: "Keep going!",
    sinceJoining: "Since joining", dhikrCounted: "dhikr counted", thisWeek: "This Week",
    rankTitle: "Competition", rankSub: "Compete in Good Deeds",
    rankNum: "# Rank", rankPct: "Top %", rankFriends: "Friends", rankOff: "Off",
    rankOffMsg: "Ranking is hidden. Your dhikr is between you and Allah.",
    rankKeep: "Keep counting! Every dhikr brings you closer to the top.",
    ofAllUsers: "of all users",
    supportBtn: "Support This App",
    supportMsg: "This app is free. If you find it valuable, support us with a one-time contribution.",
    dhikrOfDay: "Dhikr of the Day", signIn: "Sign In", signUp: "Create Account",
    navCounter: "Tasbeeh", navDua: "Du'a", navStats: "Stats", navRanking: "Ranking",
    of: "of", email: "Email", password: "Password", name: "Your Name",
    morning: "Morning Adhkar", evening: "Evening Adhkar", travel: "Travel",
    food: "Before & After Eating", bathroom: "Entering & Leaving Bathroom",
    sleep: "Before Sleep", happiness: "Joy & Gratitude", distress: "In Times of Distress",
    mosque: "Entering & Leaving Mosque",
    settings: "Settings", soundSettings: "Sound Settings",
    tapSound: "Tap Sound", completionSound: "Completion Sound", voiceStyle: "Voice",
    noDataYet: "No data yet", startCounting: "Start counting your dhikr to see progress here.",
    rankNoData: "Complete dhikr to see your ranking among other users.",
    noDays: "No days tracked yet", signOut: "Sign Out",
    yourRank: "Your Rank", topPercent: "Top", totalUsers: "Total Users",
    noAccount: "No account?", hasAccount: "Have an account?",
    loading: "Loading...", saving: "Saving...",
    customizeCounter: "Customize Counter", moreTasbeehs: "More Tasbeehs to be added soon",
    repsPerDhikr: "Repetitions per dhikr", repsHint: "How many times to say each dhikr before moving to the next",
    startingDhikr: "Starting dhikr", startingDhikrHint: "Which dhikr to begin your counter with",
    counterPreview: "Counter preview", apply: "Apply", editBtn: "Edit",
    quick: "Quick", sunnah: "Sunnah", extended: "Extended", full: "Full",
    startsWith: "starts with", eachX: "each",
  },
  ar: {
    appName: "تسبيح", appSub: "عداد الأذكار الرقمي", tapHint: "اضغط في أي مكان على الدائرة",
    today: "اليوم", cycles: "الدورات", current: "الحالي", reset: "إعادة تعيين",
    completed: "تم", nextLoading: "الذكر التالي...",
    duaTitle: "الأدعية", duaSub: "الأدعية والأذكار",
    backToAll: "العودة لجميع الأدعية", listen: "استمع",
    statsTitle: "إحصائيات", statsSub: "تقدمك الشخصي",
    signInUnlock: "سجل دخولك لفتح الإحصائيات",
    signInDesc: "تتبع تقدمك اليومي والأسبوعي والشهري عبر جميع أجهزتك.",
    signInFree: "تسجيل الدخول مجاناً", thisMonth: "هذا الشهر", streak: "سلسلة",
    bestDay: "أفضل يوم", totalAll: "المجموع الكلي", days: "يوم", keepGoing: "استمر!",
    sinceJoining: "منذ الانضمام", dhikrCounted: "ذكر", thisWeek: "هذا الأسبوع",
    rankTitle: "المنافسة", rankSub: "تنافس في الخيرات",
    rankNum: "الترتيب", rankPct: "النسبة", rankFriends: "الأصدقاء", rankOff: "إيقاف",
    rankOffMsg: "الترتيب مخفي. ذكرك بينك وبين الله.",
    rankKeep: "استمر! كل ذكر يقربك من القمة.", ofAllUsers: "من جميع المستخدمين",
    supportBtn: "ادعم التطبيق",
    supportMsg: "هذا التطبيق مجاني. إذا وجدته مفيداً يمكنك دعمنا.",
    dhikrOfDay: "ذكر اليوم", signIn: "تسجيل الدخول", signUp: "إنشاء حساب",
    navCounter: "تسبيح", navDua: "دعاء", navStats: "إحصائيات", navRanking: "ترتيب", of: "من",
    email: "البريد الإلكتروني", password: "كلمة المرور", name: "اسمك",
    morning: "أذكار الصباح", evening: "أذكار المساء", travel: "دعاء السفر",
    food: "دعاء الطعام", bathroom: "دعاء الخلاء", sleep: "أذكار النوم",
    happiness: "دعاء الفرح", distress: "دعاء الكرب", mosque: "دعاء المسجد",
    settings: "الإعدادات", soundSettings: "إعدادات الصوت",
    tapSound: "صوت النقر", completionSound: "صوت الإنجاز", voiceStyle: "الصوت",
    noDataYet: "لا توجد بيانات بعد", startCounting: "ابدأ التسبيح لمشاهدة تقدمك.",
    rankNoData: "أكمل الأذكار لمشاهدة ترتيبك.", noDays: "لم يتم تتبع أي أيام بعد",
    signOut: "تسجيل الخروج", yourRank: "ترتيبك", topPercent: "أعلى",
    totalUsers: "إجمالي المستخدمين", noAccount: "لا حساب؟", hasAccount: "لديك حساب؟",
    loading: "جار التحميل...", saving: "جار الحفظ...",
    customizeCounter: "تخصيص العداد", moreTasbeehs: "المزيد من التسابيح قريباً",
    repsPerDhikr: "التكرارات لكل ذكر", repsHint: "كم مرة تقول كل ذكر قبل الانتقال للتالي",
    startingDhikr: "الذكر الأول", startingDhikrHint: "أي ذكر تبدأ به عدادك",
    counterPreview: "معاينة العداد", apply: "تطبيق", editBtn: "تعديل",
    quick: "سريع", sunnah: "سنة", extended: "موسع", full: "كامل",
    startsWith: "يبدأ بـ", eachX: "مرة",
  },
  id: {
    appName: "Tasbeeh", appSub: "Penghitung Dzikir Digital", tapHint: "Ketuk di mana saja pada lingkaran",
    today: "Hari Ini", cycles: "Siklus", current: "Sekarang", reset: "Reset Penghitung",
    completed: "Selesai", nextLoading: "Memuat dzikir berikutnya...",
    duaTitle: "Doa", duaSub: "Doa & Dzikir",
    backToAll: "Kembali ke semua doa", listen: "Dengarkan",
    statsTitle: "Statistik", statsSub: "Kemajuan Pribadi Anda",
    signInUnlock: "Masuk untuk membuka statistik lengkap",
    signInDesc: "Lacak kemajuan dzikir harian, mingguan, dan bulanan di semua perangkat Anda.",
    signInFree: "Masuk Gratis", thisMonth: "Bulan Ini", streak: "Streak",
    bestDay: "Hari Terbaik", totalAll: "Total Sepanjang Waktu", days: "hari", keepGoing: "Terus semangat!",
    sinceJoining: "Sejak bergabung", dhikrCounted: "dzikir dihitung", thisWeek: "Minggu Ini",
    rankTitle: "Kompetisi", rankSub: "Bersaing dalam Kebaikan",
    rankNum: "# Peringkat", rankPct: "Top %", rankFriends: "Teman", rankOff: "Nonaktif",
    rankOffMsg: "Peringkat disembunyikan. Dzikirmu hanya antara kamu dan Allah.",
    rankKeep: "Terus hitung! Setiap dzikir membawamu lebih dekat ke puncak.",
    ofAllUsers: "dari semua pengguna",
    supportBtn: "Dukung Aplikasi Ini",
    supportMsg: "Aplikasi ini gratis. Jika Anda merasa bermanfaat, dukung kami dengan kontribusi sekali bayar.",
    dhikrOfDay: "Dzikir Hari Ini", signIn: "Masuk", signUp: "Buat Akun",
    navCounter: "Tasbeeh", navDua: "Doa", navStats: "Statistik", navRanking: "Peringkat",
    of: "dari", email: "Email", password: "Kata Sandi", name: "Nama Anda",
    morning: "Dzikir Pagi", evening: "Dzikir Sore", travel: "Doa Perjalanan",
    food: "Doa Sebelum & Sesudah Makan", bathroom: "Doa Masuk & Keluar Kamar Mandi",
    sleep: "Doa Sebelum Tidur", happiness: "Doa Suka Cita", distress: "Doa Saat Kesulitan",
    mosque: "Doa Masuk & Keluar Masjid",
    settings: "Pengaturan", soundSettings: "Pengaturan Suara",
    tapSound: "Suara Ketuk", completionSound: "Suara Selesai", voiceStyle: "Suara",
    noDataYet: "Belum ada data", startCounting: "Mulai menghitung dzikir untuk melihat kemajuan.",
    rankNoData: "Selesaikan dzikir untuk melihat peringkat Anda.", noDays: "Belum ada hari yang dilacak",
    signOut: "Keluar", yourRank: "Peringkat Anda", topPercent: "Top",
    totalUsers: "Total Pengguna", noAccount: "Belum punya akun?", hasAccount: "Sudah punya akun?",
    loading: "Memuat...", saving: "Menyimpan...",
    customizeCounter: "Sesuaikan Penghitung", moreTasbeehs: "Lebih banyak Tasbih akan segera ditambahkan",
    repsPerDhikr: "Pengulangan per dzikir", repsHint: "Berapa kali mengucapkan setiap dzikir sebelum berpindah ke berikutnya",
    startingDhikr: "Dzikir awal", startingDhikrHint: "Dzikir mana untuk memulai penghitung Anda",
    counterPreview: "Pratinjau penghitung", apply: "Terapkan", editBtn: "Edit",
    quick: "Cepat", sunnah: "Sunnah", extended: "Diperpanjang", full: "Penuh",
    startsWith: "dimulai dengan", eachX: "kali",
  },
  ms: {
    appName: "Tasbeeh", appSub: "Pembilang Zikir Digital", tapHint: "Ketuk di mana sahaja pada bulatan",
    today: "Hari Ini", cycles: "Kitaran", current: "Semasa", reset: "Set Semula Pembilang",
    completed: "Selesai", nextLoading: "Memuatkan zikir seterusnya...",
    duaTitle: "Doa", duaSub: "Doa & Zikir",
    backToAll: "Kembali ke semua doa", listen: "Dengar",
    statsTitle: "Statistik", statsSub: "Kemajuan Peribadi Anda",
    signInUnlock: "Log masuk untuk membuka statistik penuh",
    signInDesc: "Jejaki kemajuan zikir harian, mingguan, dan bulanan merentasi semua peranti anda.",
    signInFree: "Log Masuk Percuma", thisMonth: "Bulan Ini", streak: "Streak",
    bestDay: "Hari Terbaik", totalAll: "Jumlah Sepanjang Masa", days: "hari", keepGoing: "Teruskan!",
    sinceJoining: "Sejak menyertai", dhikrCounted: "zikir dikira", thisWeek: "Minggu Ini",
    rankTitle: "Pertandingan", rankSub: "Bersaing dalam Kebaikan",
    rankNum: "# Kedudukan", rankPct: "Top %", rankFriends: "Rakan", rankOff: "Matikan",
    rankOffMsg: "Kedudukan disembunyikan. Zikir anda hanya antara anda dan Allah.",
    rankKeep: "Terus kira! Setiap zikir membawa anda lebih dekat ke puncak.",
    ofAllUsers: "daripada semua pengguna",
    supportBtn: "Sokong Aplikasi Ini",
    supportMsg: "Aplikasi ini percuma. Jika anda mendapatinya bermanfaat, sokong kami dengan sumbangan sekali.",
    dhikrOfDay: "Zikir Hari Ini", signIn: "Log Masuk", signUp: "Cipta Akaun",
    navCounter: "Tasbeeh", navDua: "Doa", navStats: "Statistik", navRanking: "Kedudukan",
    of: "daripada", email: "E-mel", password: "Kata Laluan", name: "Nama Anda",
    morning: "Zikir Pagi", evening: "Zikir Petang", travel: "Doa Perjalanan",
    food: "Doa Sebelum & Selepas Makan", bathroom: "Doa Masuk & Keluar Tandas",
    sleep: "Doa Sebelum Tidur", happiness: "Doa Kegembiraan", distress: "Doa Ketika Kesusahan",
    mosque: "Doa Masuk & Keluar Masjid",
    settings: "Tetapan", soundSettings: "Tetapan Bunyi",
    tapSound: "Bunyi Ketuk", completionSound: "Bunyi Selesai", voiceStyle: "Suara",
    noDataYet: "Tiada data lagi", startCounting: "Mula mengira zikir untuk melihat kemajuan.",
    rankNoData: "Selesaikan zikir untuk melihat kedudukan anda.", noDays: "Tiada hari dijejaki lagi",
    signOut: "Log Keluar", yourRank: "Kedudukan Anda", topPercent: "Top",
    totalUsers: "Jumlah Pengguna", noAccount: "Tiada akaun?", hasAccount: "Ada akaun?",
    loading: "Memuatkan...", saving: "Menyimpan...",
    customizeCounter: "Sesuaikan Pembilang", moreTasbeehs: "Lebih banyak Tasbih akan ditambah tidak lama lagi",
    repsPerDhikr: "Ulangan setiap zikir", repsHint: "Berapa kali menyebut setiap zikir sebelum berpindah ke seterusnya",
    startingDhikr: "Zikir permulaan", startingDhikrHint: "Zikir mana untuk memulakan pembilang anda",
    counterPreview: "Pratonton pembilang", apply: "Guna", editBtn: "Edit",
    quick: "Pantas", sunnah: "Sunnah", extended: "Diperpanjang", full: "Penuh",
    startsWith: "bermula dengan", eachX: "kali",
  },
  fil: {
    appName: "Tasbeeh", appSub: "Digital na Pambilang ng Dasal", tapHint: "Pindutin kahit saan sa bilog",
    today: "Ngayon", cycles: "Mga Siklo", current: "Kasalukuyan", reset: "I-reset ang Bilangan",
    completed: "Tapos na", nextLoading: "Nilo-load ang susunod na dhikr...",
    duaTitle: "Mga Dua", duaSub: "Mga Dua at Pag-alala",
    backToAll: "Bumalik sa lahat ng dua", listen: "Makinig",
    statsTitle: "Istatistika", statsSub: "Iyong Personal na Pag-unlad",
    signInUnlock: "Mag-sign in para i-unlock ang buong istatistika",
    signInDesc: "Subaybayan ang iyong araw-araw, lingguhang, at buwanang pag-unlad sa lahat ng iyong device.",
    signInFree: "Mag-sign In nang Libre", thisMonth: "Ngayong Buwan", streak: "Streak",
    bestDay: "Pinakamahusay na Araw", totalAll: "Kabuuan Sa Lahat ng Oras", days: "araw", keepGoing: "Ituloy mo!",
    sinceJoining: "Mula nang sumali", dhikrCounted: "dhikr nabibilang", thisWeek: "Ngayong Linggo",
    rankTitle: "Kompetisyon", rankSub: "Makipagsabayan sa Kabutihan",
    rankNum: "# Ranggo", rankPct: "Nangungunang %", rankFriends: "Mga Kaibigan", rankOff: "Patayin",
    rankOffMsg: "Nakatago ang ranggo. Ang iyong dhikr ay nasa pagitan mo at ng Allah.",
    rankKeep: "Ituloy ang pagbibilang! Bawat dhikr ay nagdadala sa iyo na mas malapit sa tuktok.",
    ofAllUsers: "ng lahat ng gumagamit",
    supportBtn: "Suportahan ang App na Ito",
    supportMsg: "Ang app na ito ay libre. Kung makita mong kapaki-pakinabang, suportahan kami ng isang beses na kontribusyon.",
    dhikrOfDay: "Dhikr ng Araw", signIn: "Mag-sign In", signUp: "Lumikha ng Account",
    navCounter: "Tasbeeh", navDua: "Dua", navStats: "Istatistika", navRanking: "Ranggo",
    of: "ng", email: "Email", password: "Password", name: "Iyong Pangalan",
    morning: "Umaga Adhkar", evening: "Gabi Adhkar", travel: "Paglalakbay",
    food: "Bago at Pagkatapos Kumain", bathroom: "Pagpasok at Paglabas sa Banyo",
    sleep: "Bago Matulog", happiness: "Kagalakan at Pasasalamat", distress: "Sa Panahon ng Kahirapan",
    mosque: "Pagpasok at Paglabas sa Masjid",
    settings: "Mga Setting", soundSettings: "Mga Setting ng Tunog",
    tapSound: "Tunog ng Tap", completionSound: "Tunog ng Pagkumpleto", voiceStyle: "Boses",
    noDataYet: "Wala pang data", startCounting: "Simulan ang pagbibilang ng dhikr para makita ang pag-unlad.",
    rankNoData: "Kumpletuhin ang dhikr para makita ang iyong ranggo.", noDays: "Wala pang araw na nasubaybayan",
    signOut: "Mag-sign Out", yourRank: "Iyong Ranggo", topPercent: "Nangungunang",
    totalUsers: "Kabuuang Mga Gumagamit", noAccount: "Walang account?", hasAccount: "May account na?",
    loading: "Nilo-load...", saving: "Sino-save...",
    customizeCounter: "I-customize ang Bilangan", moreTasbeehs: "Mas maraming Tasbeeh ang idadagdag sa lalong madaling panahon",
    repsPerDhikr: "Mga pag-ulit bawat dhikr", repsHint: "Ilang beses sabihin ang bawat dhikr bago lumipat sa susunod",
    startingDhikr: "Simula ng dhikr", startingDhikrHint: "Aling dhikr ang magsisimula ng iyong bilangan",
    counterPreview: "Preview ng bilangan", apply: "Ilapat", editBtn: "I-edit",
    quick: "Mabilis", sunnah: "Sunnah", extended: "Matagal", full: "Buo",
    startsWith: "nagsisimula sa", eachX: "beses",
  },
};

export const LANG_LABELS: Record<string, string> = {
  en: "English", ar: "العربية", id: "Indonesia", ms: "Melayu", fil: "Filipino",
};

export const DHIKR_SEQUENCE = [
  { arabic: "سُبْحَانَ اللَّهِ", transliteration: "SubhanAllah", meaning: { en: "Glory be to Allah", ar: "تنزيه الله عن كل نقص", id: "Maha Suci Allah", ms: "Maha Suci Allah", fil: "Kaluwalhatian sa Allah" }, target: 33 },
  { arabic: "الْحَمْدُ لِلَّهِ", transliteration: "Alhamdulillah", meaning: { en: "Praise be to Allah", ar: "الثناء لله", id: "Segala Puji Bagi Allah", ms: "Segala Puji Bagi Allah", fil: "Papuri sa Allah" }, target: 33 },
  { arabic: "اللَّهُ أَكْبَرُ", transliteration: "Allahu Akbar", meaning: { en: "Allah is the Greatest", ar: "الله أعظم من كل شيء", id: "Allah Maha Besar", ms: "Allah Maha Besar", fil: "Ang Allah ang Pinakadakila" }, target: 33 },
  { arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ", transliteration: "La ilaha illallah", meaning: { en: "There is no god but Allah", ar: "لا معبود بحق إلا الله", id: "Tiada Tuhan Selain Allah", ms: "Tiada Tuhan Melainkan Allah", fil: "Walang diyos kundi Allah" }, target: 1 },
];

export const DAILY_DHIKR_DB = [
  { arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", transliteration: "HasbunAllahu wa ni'mal wakeel", en: "Allah is sufficient for us and He is the best disposer of affairs", ar: "حسبنا الله ونعم الوكيل", id: "Allah cukup bagi kami dan Dia sebaik-baik pelindung", ms: "Allah cukup bagi kami dan Dia sebaik-baik Pelindung", fil: "Ang Allah ay sapat para sa amin at Siya ang pinakamahusay na tagapamahala" },
  { arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "La hawla wa la quwwata illa billah", en: "There is no power nor strength except with Allah", ar: "لا حول ولا قوة إلا بالله", id: "Tiada daya dan kekuatan kecuali dengan Allah", ms: "Tiada daya dan kekuatan melainkan dengan Allah", fil: "Walang kapangyarihan at lakas maliban sa Allah" },
  { arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ", transliteration: "Astaghfirullah al-'Azeem", en: "I seek forgiveness from Allah, the Almighty", ar: "أستغفر الله العظيم", id: "Aku mohon ampun kepada Allah Yang Maha Agung", ms: "Aku memohon keampunan daripada Allah Yang Maha Agung", fil: "Humihingi ako ng kapatawaran mula sa Allah, ang Makapangyarihan" },
  { arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", transliteration: "SubhanAllahi wa bihamdihi", en: "Glory be to Allah and His is the praise", ar: "سبحان الله وبحمده", id: "Maha Suci Allah dan segala puji bagi-Nya", ms: "Maha Suci Allah dan segala puji bagi-Nya", fil: "Kaluwalhatian sa Allah at sa Kanya ang papuri" },
  { arabic: "سُبْحَانَ اللَّهِ الْعَظِيمِ", transliteration: "SubhanAllah il-'Azeem", en: "Glory be to Allah, the Almighty", ar: "سبحان الله العظيم", id: "Maha Suci Allah Yang Maha Agung", ms: "Maha Suci Allah Yang Maha Agung", fil: "Kaluwalhatian sa Allah, ang Makapangyarihan" },
  { arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", transliteration: "Allahumma salli 'ala Muhammad", en: "O Allah, send blessings upon Muhammad", ar: "اللهم صل على محمد", id: "Ya Allah, curahkan rahmat atas Muhammad", ms: "Ya Allah, cucurilah rahmat ke atas Muhammad", fil: "O Allah, ipadala ang mga pagpapala kay Muhammad" },
  { arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ", transliteration: "La ilaha illallahu wahdahu la sharika lah", en: "There is no god but Allah alone, with no partner", ar: "لا إله إلا الله وحده لا شريك له", id: "Tiada Tuhan selain Allah semata, tidak ada sekutu bagi-Nya", ms: "Tiada tuhan melainkan Allah sahaja, tiada sekutu bagi-Nya", fil: "Walang diyos kundi Allah nag-iisa, walang katambal" },
  { arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ", transliteration: "Rabbighfir li wa tub 'alayya", en: "My Lord, forgive me and accept my repentance", ar: "ربي اغفر لي وتب علي", id: "Ya Tuhanku, ampunilah aku dan terimalah taubatku", ms: "Ya Tuhanku, ampunilah aku dan terimalah taubatku", fil: "Panginoon ko, patawarin mo ako at tanggapin ang aking pagsisisi" },
  { arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ", transliteration: "Ya Hayyu ya Qayyum birahmatika astaghith", en: "O Ever-Living, O Sustainer, in Your mercy I seek relief", ar: "يا حي يا قيوم برحمتك أستغيث", id: "Wahai Yang Maha Hidup, Yang Maha Berdiri Sendiri, dengan rahmat-Mu aku memohon pertolongan", ms: "Wahai Yang Maha Hidup, Yang Maha Berdiri Sendiri, dengan rahmat-Mu aku memohon pertolongan", fil: "O Buhay na Walang Hanggan, O Sustainer, sa Iyong awa ay humihingi ako ng ginhawa" },
  { arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa", en: "O Allah, You are the Pardoner, You love to pardon, so pardon me", ar: "اللهم إنك عفو تحب العفو فاعف عني", id: "Ya Allah, sesungguhnya Engkau Maha Pemaaf, menyukai maaf, maka maafkanlah aku", ms: "Ya Allah, sesungguhnya Engkau Maha Pemaaf, menyukai kemaafan, maka maafkanlah aku", fil: "O Allah, Ikaw ang Nagpapatawad, mahilig Kang magpatawad, kaya patawarin mo ako" },
  { arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", transliteration: "Rabbana atina fid-dunya hasanah", en: "Our Lord, give us good in this world and good in the Hereafter", ar: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة", id: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat", ms: "Ya Tuhan kami, kurniakanlah kami kebaikan di dunia dan kebaikan di akhirat", fil: "Panginoon namin, ibigay mo sa amin ang mabuti sa mundong ito at mabuti sa Kabilang-buhay" },
  { arabic: "رَبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni 'ilma", en: "My Lord, increase me in knowledge", ar: "رب زدني علماً", id: "Ya Tuhanku, tambahkanlah ilmuku", ms: "Ya Tuhanku, tambahkanlah ilmuku", fil: "Panginoon ko, dagdagan mo ako ng kaalaman" },
  { arabic: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa anta subhanaka", en: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers", ar: "لا إله إلا أنت سبحانك إني كنت من الظالمين", id: "Tiada tuhan kecuali Engkau, Maha Suci Engkau, sesungguhnya aku termasuk orang-orang yang zalim", ms: "Tiada tuhan melainkan Engkau, Maha Suci Engkau, sesungguhnya aku termasuk orang-orang yang zalim", fil: "Walang diyos maliban sa Iyo; luwalhati sa Iyo. Katotohanan, ako ay kabilang sa mga gumagawa ng masama" },
  { arabic: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَاللَّهُ أَكْبَرُ", transliteration: "SubhanAllahi walhamdulillahi wallahu akbar", en: "Glory be to Allah, praise be to Allah, Allah is the Greatest", ar: "سبحان الله والحمد لله والله أكبر", id: "Maha Suci Allah, segala puji bagi Allah, Allah Maha Besar", ms: "Maha Suci Allah, segala puji bagi Allah, Allah Maha Besar", fil: "Kaluwalhatian sa Allah, papuri sa Allah, ang Allah ang Pinakadakila" },
  { arabic: "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا", transliteration: "Allahummaj'al fi qalbi nura", en: "O Allah, place light in my heart", ar: "اللهم اجعل في قلبي نوراً", id: "Ya Allah, jadikanlah cahaya dalam hatiku", ms: "Ya Allah, jadikanlah cahaya dalam hatiku", fil: "O Allah, ilagay mo ang liwanag sa aking puso" },
];

export const DUAA_CATEGORIES = [
  { id: "morning", icon: "🌅", nameKey: "morning", nameAr: "أذكار الصباح", items: [
    { arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ", transliteration: "Asbahna wa asbahal mulku lillah", meaning: { en: "We have reached the morning and the kingdom belongs to Allah", ar: "بدأنا الصباح والملك كله لله", id: "Kami memasuki pagi dan kerajaan milik Allah", ms: "Kami memasuki pagi dan kerajaan kepunyaan Allah", fil: "Nakarating tayo sa umaga at ang kaharian ay pag-aari ng Allah" } },
    { arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ", transliteration: "Allahumma bika asbahna wa bika amsayna", meaning: { en: "O Allah, by You we enter the morning and by You we enter the evening", ar: "اللهم بك نبدأ صباحنا ومساءنا", id: "Ya Allah, dengan-Mu kami memasuki pagi dan dengan-Mu kami memasuki sore", ms: "Ya Allah, dengan-Mu kami memasuki pagi dan dengan-Mu kami memasuki petang", fil: "O Allah, sa Iyo tayo pumapasok sa umaga at sa Iyo tayo pumapasok sa gabi" } },
  ]},
  { id: "evening", icon: "🌙", nameKey: "evening", nameAr: "أذكار المساء", items: [
    { arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ", transliteration: "Amsayna wa amsal mulku lillah", meaning: { en: "We have reached the evening and the kingdom belongs to Allah", ar: "بدأنا المساء والملك كله لله", id: "Kami memasuki sore dan kerajaan milik Allah", ms: "Kami memasuki petang dan kerajaan kepunyaan Allah", fil: "Nakarating tayo sa gabi at ang kaharian ay pag-aari ng Allah" } },
    { arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا", transliteration: "Allahumma bika amsayna wa bika asbahna", meaning: { en: "O Allah, by You we enter the evening and by You we enter the morning", ar: "اللهم بك أمسينا وبك أصبحنا", id: "Ya Allah, dengan-Mu kami memasuki sore dan dengan-Mu kami memasuki pagi", ms: "Ya Allah, dengan-Mu kami memasuki petang dan dengan-Mu kami memasuki pagi", fil: "O Allah, sa Iyo tayo pumapasok sa gabi at sa Iyo tayo pumapasok sa umaga" } },
  ]},
  { id: "travel", icon: "✈️", nameKey: "travel", nameAr: "دعاء السفر", items: [
    { arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ", transliteration: "Subhanal-ladhi sakh-khara lana hadha", meaning: { en: "Glory to Him who has subjected this to us", ar: "سبحان من سخر لنا هذا", id: "Maha Suci Dia yang telah menundukkan ini untuk kami", ms: "Maha Suci Dia yang telah menundukkan ini untuk kami", fil: "Kaluwalhatian sa Kanya na nagpasakop nito sa atin" } },
    { arabic: "اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ", transliteration: "Allahumma hawwin 'alayna safarana", meaning: { en: "O Allah, make this journey easy for us and shorten its distance", ar: "اللهم هون علينا سفرنا هذا", id: "Ya Allah, mudahkanlah perjalanan kami dan pendekkan jaraknya", ms: "Ya Allah, permudahkanlah perjalanan kami dan pendekkan jaraknya", fil: "O Allah, gawing madali ang paglalakbay na ito para sa amin at paikliin ang distansya nito" } },
  ]},
  { id: "food", icon: "🍽️", nameKey: "food", nameAr: "دعاء الطعام", items: [
    { arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ", transliteration: "Bismillah wa 'ala barakatillah", meaning: { en: "In the name of Allah and with the blessings of Allah", ar: "بسم الله وعلى بركة الله", id: "Dengan nama Allah dan atas berkah Allah", ms: "Dengan nama Allah dan dengan berkat Allah", fil: "Sa pangalan ng Allah at sa mga pagpapala ng Allah" } },
    { arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", transliteration: "Alhamdulillahil-ladhi at'amana wa saqana", meaning: { en: "Praise be to Allah who fed us, gave us drink, and made us Muslims", ar: "الحمد لله الذي أطعمنا وسقانا وجعلنا مسلمين", id: "Segala puji bagi Allah yang telah memberi kami makan, minum, dan menjadikan kami Muslim", ms: "Segala puji bagi Allah yang memberi kami makan, minum, dan menjadikan kami Muslim", fil: "Papuri sa Allah na nagpakain sa atin, nagpainom, at ginawa tayong mga Muslim" } },
  ]},
  { id: "sleep", icon: "😴", nameKey: "sleep", nameAr: "أذكار النوم", items: [
    { arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismika Allahumma amutu wa ahya", meaning: { en: "In Your name, O Allah, I die and I live", ar: "باسمك اللهم أموت وأحيا", id: "Dengan nama-Mu ya Allah, aku mati dan aku hidup", ms: "Dengan nama-Mu ya Allah, aku mati dan aku hidup", fil: "Sa Iyong pangalan, O Allah, ako ay namamatay at nabubuhay" } },
    { arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak", meaning: { en: "O Allah, protect me from Your punishment on the Day of Resurrection", ar: "اللهم قني عذابك يوم تبعث عبادك", id: "Ya Allah, lindungi aku dari azab-Mu pada hari kebangkitan", ms: "Ya Allah, lindungilah aku dari azab-Mu pada hari kebangkitan", fil: "O Allah, protektahan mo ako mula sa Iyong parusa sa Araw ng Muling Pagkabuhay" } },
  ]},
  { id: "distress", icon: "🤲", nameKey: "distress", nameAr: "دعاء الكرب", items: [
    { arabic: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimin", meaning: { en: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers", ar: "لا إله إلا أنت سبحانك إني كنت من الظالمين", id: "Tiada tuhan kecuali Engkau, Maha Suci Engkau, sesungguhnya aku termasuk orang-orang yang zalim", ms: "Tiada tuhan melainkan Engkau, Maha Suci Engkau, sesungguhnya aku termasuk orang-orang yang zalim", fil: "Walang diyos maliban sa Iyo; luwalhati sa Iyo. Katotohanan, ako ay kabilang sa mga gumagawa ng masama" } },
    { arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", transliteration: "HasbunAllahu wa ni'mal wakeel", meaning: { en: "Allah is sufficient for us and He is the best disposer of affairs", ar: "حسبنا الله ونعم الوكيل", id: "Allah cukup bagi kami dan Dia sebaik-baik pelindung", ms: "Allah cukup bagi kami dan Dia sebaik-baik Pelindung", fil: "Ang Allah ay sapat para sa amin at Siya ang pinakamahusay na tagapamahala" } },
  ]},
  { id: "mosque", icon: "🕌", nameKey: "mosque", nameAr: "دعاء المسجد", items: [
    { arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", transliteration: "Allahummaf-tah li abwaba rahmatik", meaning: { en: "O Allah, open the doors of Your mercy for me", ar: "اللهم افتح لي أبواب رحمتك", id: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu", ms: "Ya Allah, bukakanlah bagiku pintu-pintu rahmat-Mu", fil: "O Allah, buksan mo para sa akin ang mga pintuan ng Iyong habag" } },
    { arabic: "اللَّهُمَّ اعْصِمْنِي مِنَ الشَّيْطَانِ الرَّجِيمِ", transliteration: "Allahumma a'simni minash-shaytanir-rajim", meaning: { en: "O Allah, protect me from the accursed devil", ar: "اللهم اعصمني من الشيطان الرجيم", id: "Ya Allah, lindungi aku dari setan yang terkutuk", ms: "Ya Allah, lindungilah aku daripada syaitan yang direjam", fil: "O Allah, protektahan mo ako mula sa isinumpang diyablo" } },
  ]},
  { id: "happiness", icon: "😊", nameKey: "happiness", nameAr: "دعاء الفرح", items: [
    { arabic: "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ", transliteration: "Alhamdulillahil-ladhi bini'matihi tatimmus-salihat", meaning: { en: "Praise be to Allah by whose grace good deeds are completed", ar: "الحمد لله الذي بنعمته تتم الصالحات", id: "Segala puji bagi Allah yang dengan nikmat-Nya sempurnalah amal-amal yang baik", ms: "Segala puji bagi Allah yang dengan nikmat-Nya sempurnalah amalan-amalan yang baik", fil: "Papuri sa Allah na sa Kanyang biyaya ay nakukumpleto ang mga mabuting gawa" } },
  ]},
];
